<?xml version="1.0" encoding="utf-8"?><Database Name="DFF" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=RAIHAN-PC\SQLEXPRESS;Initial Catalog=DFF;Integrated Security=True" SettingsObjectName="FastFoodManagementSystem.Properties.Settings" SettingsPropertyName="DFFConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Employees" Member="Employees">
    <Type Name="Employee">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="Birthdate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NID" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Salary" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Employee_Sell" Member="Sells" ThisKey="ID" OtherKey="CreatedBy" Type="Sell" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="P_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="P_Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="P_Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="P_Status" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Product_Sell_Detail" Member="Sell_Details" ThisKey="P_Id" OtherKey="Product_ID" Type="Sell_Detail" />
    </Type>
  </Table>
  <Table Name="dbo.Sell_Details" Member="Sell_Details">
    <Type Name="Sell_Detail">
      <Column Name="SD_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Product_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="P_Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="P_Cost" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Sell_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_Sell_Detail" Member="Product" ThisKey="Product_ID" OtherKey="P_Id" Type="Product" IsForeignKey="true" />
      <Association Name="Sell_Sell_Detail" Member="Sell" ThisKey="Sell_ID" OtherKey="SellId" Type="Sell" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Sells" Member="Sells">
    <Type Name="Sell">
      <Column Name="SellId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SellDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Cost" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Discount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Vat" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TotalCost" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Sell_Sell_Detail" Member="Sell_Details" ThisKey="SellId" OtherKey="Sell_ID" Type="Sell_Detail" />
      <Association Name="Employee_Sell" Member="Employee" ThisKey="CreatedBy" OtherKey="ID" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
</Database>